name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: mkdir -p dist
    - run: cp -rp *.png dist
    - run: cp -rp *.jpg dist
    - run: cp -rp *.ico dist
    - run: cp -rp *.svg dist
    - run: cp -rp *.sketch dist

    - name: Website
      working-directory: dist
      run: |
        cat > index.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Source files of uivjs's logo.</title>
          <style>
            .header { color: #333; text-align: center; padding: 80px 0 60px 0; min-height: 153px; font-size: 14px; }
            .content { text-align: center; }
            .content a span { display: inline-block; padding-top: 10px; padding-bottom: 10px; }
            .content a img { height: 60px; }
            .content a {
              display: inline-flex;
              justify-content: center;
              align-items: center;
              flex-direction: column;
              font-size: 12px;
              width: 120px;
              height: 120px;
              background-color: #e8e8e8;
              margin-top: 10px;
              padding: 16px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <img src="./logo.svg" alt="uivjs logo" width="120" />
          </div>
          <div class="content">
            <a href="./favicon.ico" target="_blank">
              <img src="./favicon.ico" alt="uivjs favicon ico" />
              <span>favicon.ico</span>
            </a>
            <a href="./logo.svg" target="_blank">
              <img src="./logo.svg" alt="uivjs logo svg" />
              <span>logo.svg</span>
            </a>
            <a href="./uivjs.sketch" target="_blank">
              <img src="./logo.svg" alt="uivjs sketch" />
              <span>uivjs.sketch</span>
            </a>
          </div>
          <div class="content">
            <a href="./favicon-16x16.png" target="_blank">
              <img src="./favicon-16x16.png" alt="uivjs favicon 16x16" />
              <span>favicon-16x16.png</span>
            </a>
            <a href="./favicon-32x32.png" target="_blank">
              <img src="./favicon-32x32.png" alt="uivjs favicon" />
              <span>favicon-32x32.png</span>
            </a>
            <a href="./android-chrome-512x512.png" target="_blank">
              <img src="./android-chrome-512x512.png" alt="uivjs android chrome 512x512" />
              <span>android-chrome-512x512.png</span>
            </a>
            <a href="./android-chrome-192x192.png" target="_blank">
              <img src="./android-chrome-192x192.png" alt="uivjs android chrome 192x192" />
              <span>android-chrome-192x192.png</span>
            </a>
            <a href="./safari-pinned-tab.svg" target="_blank">
              <img src="./safari-pinned-tab.svg" alt="uivjs android chrome 192x192" />
              <span>safari-pinned-tab.svg</span>
            </a>
          </div>
        </body>
        </html>
        EOF
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist