name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: mkdir -p dist
    - run: cp -rp *.png dist
    - run: cp -rp *.jpg dist
    # - run: cp -rp *.ico dist
    - run: cp -rp *.svg dist
    - run: cp -rp *.sketch dist

    - name: Website
      working-directory: dist
      run: |
        cat > index.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Source files of kktjs's logo.</title>
          <style>
            .header { color: #333; text-align: center; padding: 80px 0 60px 0; min-height: 153px; font-size: 14px; }
            .content { text-align: center; }
            .content a span { display: inline-block; padding-top: 10px; padding-bottom: 10px; }
            .content a img { height: 60px; }
            .content a {
              display: inline-flex;
              justify-content: center;
              align-items: center;
              flex-direction: column;
              font-size: 12px;
              width: 120px;
              height: 120px;
              background-color: #e8e8e8;
              margin-top: 10px;
              padding: 16px;
            }
            .footer { text-align: center; line-height: 20px; padding: 10px 0 20px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <img src="./kkt.svg" alt="kktjs logo" width="120" />
          </div>
          <div class="content">
            <a href="./kkt.svg" target="_blank">
              <img src="./kkt.svg" alt="kktjs logo svg" />
              <span>kkt.svg</span>
            </a>
            <a href="./kkt@2x.png" target="_blank">
              <img src="./kkt@2x.png" alt="kktjs logo svg" />
              <span>kkt@2x.png</span>
            </a>
            <a href="./kkt@2x.jpg" target="_blank">
              <img src="./kkt@2x.jpg" alt="kktjs logo svg" />
              <span>kkt@2x.jpg</span>
            </a>
            <a href="./kkt@3x.png" target="_blank">
              <img src="./kkt@3x.png" alt="kktjs logo svg" />
              <span>kkt@3x.png</span>
            </a>
            <a href="./kktjs.sketch" target="_blank">
              <img src="./kkt.svg" alt="kktjs sketch" />
              <span>kktjs.sketch</span>
            </a>
          </div>
          <div class="footer">
            Licensed under MIT. (Yes it's free, <a href="https://github.com/kktjs/logo" target="_blank">Github</a>)
            <div>
              Copyright 2021~present <a href="http://github.com/jaywcjlove" target="_blank">Kenny Wong</a>. 
            </div>
          </div>
        </body>
        </html>
        EOF
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist